/**
 * Recurring Schedule CRUD
 * Creates, lists, and deletes persistent recurring schedule workflows.
 */

import * as fs from 'fs';
import * as path from 'path';
import { generateScheduleWorkflow, generateId, type ScheduleAction } from '../github/workflows';
import { type Config } from '../config';

export interface ScheduleInfo {
  id: string;
  name: string;
  cronExpression: string;
  filePath: string;
  createdAt: string;
}

/**
 * Create a recurring schedule workflow
 */
export async function createSchedule(
  repoPath: string,
  name: string,
  cronExpression: string,
  action: ScheduleAction,
  config: Config
): Promise<{ id: string }> {
  const id = generateId();
  const yaml = generateScheduleWorkflow(id, name, cronExpression, action);
  const workflowPath = path.join(repoPath, '.github', 'workflows', `sched-${id}.yml`);

  fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
  fs.writeFileSync(workflowPath, yaml);

  return { id };
}

/**
 * List all active schedules by scanning workflow files
 */
export function listSchedules(repoPath: string): ScheduleInfo[] {
  const workflowDir = path.join(repoPath, '.github', 'workflows');
  if (!fs.existsSync(workflowDir)) return [];

  const files = fs.readdirSync(workflowDir).filter(f => f.startsWith('sched-') && f.endsWith('.yml'));

  return files.map(file => {
    const filePath = path.join(workflowDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const id = file.replace('sched-', '').replace('.yml', '');

    // Parse name from YAML
    const nameMatch = content.match(/^name:\s*"?Schedule:\s*(.+?)"?\s*$/m);
    const name = nameMatch?.[1] || 'Unknown';

    // Parse cron from YAML
    const cronMatch = content.match(/cron:\s*'([^']+)'/);
    const cronExpression = cronMatch?.[1] || 'unknown';

    const stat = fs.statSync(filePath);

    return {
      id,
      name,
      cronExpression,
      filePath,
      createdAt: stat.birthtime.toISOString(),
    };
  });
}

/**
 * Validate that an ID is safe (hex characters only, generated by generateId).
 * Prevents path traversal via crafted IDs containing '../'.
 */
function validateId(id: string): void {
  if (!/^[a-f0-9]+$/.test(id)) {
    throw new Error('Invalid ID format');
  }
}

/**
 * Delete a recurring schedule
 */
export async function deleteSchedule(repoPath: string, id: string): Promise<boolean> {
  validateId(id);
  const filePath = path.join(repoPath, '.github', 'workflows', `sched-${id}.yml`);
  if (!fs.existsSync(filePath)) return false;
  try {
    fs.unlinkSync(filePath);
  } catch {
    return false;
  }
  return true;
}
