/**
 * Reminder CRUD
 * Creates, lists, and cancels one-shot reminder workflows.
 * Writes workflow YAML to local repo clone; sync pushes them to GitHub.
 */

import * as fs from 'fs';
import * as path from 'path';
import { generateReminderWorkflow, generateId } from '../github/workflows';
import { type Config } from '../config';

export interface ReminderInfo {
  id: string;
  message: string;
  cronExpression: string;
  filePath: string;
  createdAt: string;
}

/**
 * Create a reminder by writing a workflow YAML to the repo
 */
export async function createReminder(
  repoPath: string,
  message: string,
  cronExpression: string,
  config: Config,
  humanReadable?: string
): Promise<{ id: string; humanReadable: string }> {
  const id = generateId();
  const chatId = config.telegram.allowedGroupId?.toString() || '';
  const threadId = config.telegram.allowedTopicIds?.[0]?.toString();
  const channel = config.channels.active;

  const yaml = generateReminderWorkflow(id, message, cronExpression, chatId, threadId, channel);
  const workflowPath = path.join(repoPath, '.github', 'workflows', `remind-${id}.yml`);

  fs.mkdirSync(path.dirname(workflowPath), { recursive: true });
  fs.writeFileSync(workflowPath, yaml);

  return { id, humanReadable: humanReadable || cronExpression };
}

/**
 * List all active reminders by scanning workflow files
 */
export function listReminders(repoPath: string): ReminderInfo[] {
  const workflowDir = path.join(repoPath, '.github', 'workflows');
  if (!fs.existsSync(workflowDir)) return [];

  const files = fs.readdirSync(workflowDir).filter(f => f.startsWith('remind-') && f.endsWith('.yml'));

  return files.map(file => {
    const filePath = path.join(workflowDir, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const id = file.replace('remind-', '').replace('.yml', '');

    // Parse name from YAML
    const nameMatch = content.match(/^name:\s*"?Reminder:\s*(.+?)"?\s*$/m);
    const message = nameMatch?.[1] || 'Unknown';

    // Parse cron from YAML
    const cronMatch = content.match(/cron:\s*'([^']+)'/);
    const cronExpression = cronMatch?.[1] || 'unknown';

    // Get file creation time as created date
    const stat = fs.statSync(filePath);

    return {
      id,
      message,
      cronExpression,
      filePath,
      createdAt: stat.birthtime.toISOString(),
    };
  });
}

/**
 * Validate that an ID is safe (hex characters only, generated by generateId).
 * Prevents path traversal via crafted IDs containing '../'.
 */
function validateId(id: string): void {
  if (!/^[a-f0-9]+$/.test(id)) {
    throw new Error('Invalid ID format');
  }
}

/**
 * Cancel a reminder by deleting its workflow file
 */
export async function cancelReminder(repoPath: string, id: string): Promise<boolean> {
  validateId(id);
  const filePath = path.join(repoPath, '.github', 'workflows', `remind-${id}.yml`);
  if (!fs.existsSync(filePath)) return false;
  try {
    fs.unlinkSync(filePath);
  } catch {
    return false;
  }
  return true;
}
